### ISSUE TITLE
Experiment(Table3)

### ISSUE THREAD

**Issue by jw9603** [raruidol/ArgumentMining23-Fallacy#3]
Hi,

How did you proceed with the Random baseline in Table 3 of your paper?

**Comment by raruidol** [comment]
Hi,

For the random baseline in general, I randomly assigned a class to each text sample. Specifically in the case of Table 3, since it is comparing the performance in the 5-class classification problem, the random baseline randomly assigns one of the five possible classes as the label.

Hope this helps,
Ramon
